# Generated by Django 3.2.4 on 2021-06-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='interal_page',
            new_name='internal_page',
        ),
    ]
